import courseImage from "../assets/course-image.png";

const mockCourses = [
  {
    id: 1,
    title: "COSC 306 - Web Programming",
    category: "Computer Science",
    level: "300 Level",
    tags: ["Project Support", "Assignment Discussion", "Q&A", "Frontend Help", "Study Group"],
    memberCount: 167,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },
  {
    id: 2,
    title: "MATH 200 - Multivariable Calculus",
    category: "Mathematics",
    level: "200 Level",
    tags: ["Study Group", "Practice Sets", "Homework Help"],
    memberCount: 84,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: false,
  },
  {
    id: 3,
    title: "Coding Interview Prep",
    category: "Computer Science",
    level: "Career Development",
    tags: ["Mock Interviews", "Resume Review", "LeetCode Practice", "Peer Feedback"],
    memberCount: 92,
    location: "Remote",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },  {
    id: 1,
    title: "COSC 306 - Web Programming",
    category: "Computer Science",
    level: "300 Level",
    tags: ["Project Support", "Assignment Discussion", "Q&A", "Frontend Help", "Study Group"],
    memberCount: 167,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },  {
    id: 1,
    title: "COSC 306 - Web Programming",
    category: "Computer Science",
    level: "300 Level",
    tags: ["Project Support", "Assignment Discussion", "Q&A", "Frontend Help", "Study Group"],
    memberCount: 167,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },  {
    id: 1,
    title: "COSC 306 - Web Programming",
    category: "Computer Science",
    level: "300 Level",
    tags: ["Project Support", "Assignment Discussion", "Q&A", "Frontend Help", "Study Group"],
    memberCount: 167,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },  {
    id: 1,
    title: "COSC 306 - Web Programming",
    category: "Computer Science",
    level: "300 Level",
    tags: ["Project Support", "Assignment Discussion", "Q&A", "Frontend Help", "Study Group"],
    memberCount: 167,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },  {
    id: 1,
    title: "COSC 306 - Web Programming",
    category: "Computer Science",
    level: "300 Level",
    tags: ["Project Support", "Assignment Discussion", "Q&A", "Frontend Help", "Study Group"],
    memberCount: 167,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },{
    id: 1,
    title: "COSC 306 - Web Programming",
    category: "Computer Science",
    level: "300 Level",
    tags: ["Project Support", "Assignment Discussion", "Q&A", "Frontend Help", "Study Group"],
    memberCount: 167,
    location: "Remote + Campus",
    joinType: "Open to Join",
    imageUrl: courseImage,
    isFeatured: true,
  },
];

export default mockCourses;